# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: SSH Remote Commands
      uses: appleboy/ssh-action@v1.0.3
      with:
          # ssh remote host
          host: ${{secrets.SERVER_IP}}
          # ssh remote user
          username: ${{secrets.SERVER_USERNAME}}
          # ssh remote password
          password: ${{secrets.SERVER_PASSWORD}}
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            npm --help
            cd htdocs/berles.gemes.eu/
            git pull
            npm install
            npm run build
            pm2 start lakasberles
